apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-platform-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-platform-api
  template:
    metadata:
      labels:
        app: cloud-platform-api
    spec:
      containers:
        - name: api
          image: cloud-platform-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
