apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-platform-api
spec:
  rules:
    - host: cloud.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-platform-api
                port:
                  number: 80
